import { esColors, esTheme } from '../../educacionSuperior/esTheme';

export const cpStyles = {
    pageStack: {
        display: 'flex',
        flexDirection: 'column',
        gap: 20,
    },
    toolbar: {
        display: 'flex',
        flexWrap: 'wrap',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 12,
    },
    toolbarFilters: {
        display: 'flex',
        flexWrap: 'wrap',
        alignItems: 'center',
        gap: 10,
        flex: 1,
    },
    masterDetail: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 320px), 1fr))',
        gap: 16,
        alignItems: 'start',
    },
    masterDetailSingle: {
        display: 'grid',
        gridTemplateColumns: '1fr',
        gap: 16,
    },
    listCard: {
        ...esTheme.card,
        overflow: 'hidden',
    },
    listHeader: {
        padding: '14px 16px',
        borderBottom: `1px solid ${esColors.border}`,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 8,
    },
    listHeaderTitle: {
        margin: 0,
        fontSize: 14,
        fontWeight: 700,
        color: esColors.text,
    },
    listHeaderMeta: {
        margin: 0,
        fontSize: 12,
        color: esColors.muted,
    },
    cicloRow: {
        display: 'grid',
        gridTemplateColumns: 'auto 1fr auto',
        gap: 12,
        alignItems: 'center',
        padding: '14px 16px',
        borderBottom: `1px solid ${esColors.rowBorder}`,
        cursor: 'pointer',
        transition: 'background 0.15s',
    },
    cicloRowSelected: {
        background: '#EFF6FF',
        borderLeft: `3px solid ${esColors.primary}`,
        paddingLeft: 13,
    },
    cicloRowClave: {
        fontSize: 12,
        fontWeight: 700,
        color: esColors.primary,
        fontFamily: 'ui-monospace, monospace',
    },
    cicloRowNombre: {
        margin: '2px 0 0',
        fontSize: 14,
        fontWeight: 600,
        color: esColors.text,
    },
    cicloRowFechas: {
        margin: '4px 0 0',
        fontSize: 12,
        color: esColors.muted,
    },
    detailPanel: {
        ...esTheme.card,
        position: 'sticky',
        top: 16,
        maxHeight: 'calc(100vh - 120px)',
        overflow: 'auto',
    },
    detailHeader: {
        padding: '18px 20px',
        borderBottom: `1px solid ${esColors.border}`,
    },
    detailTitle: {
        margin: '0 0 4px',
        fontSize: 17,
        fontWeight: 700,
        color: esColors.text,
    },
    detailClave: {
        margin: 0,
        fontSize: 12,
        color: esColors.muted,
        fontFamily: 'ui-monospace, monospace',
    },
    detailBody: {
        padding: '16px 20px 20px',
    },
    detailMetaGrid: {
        display: 'grid',
        gridTemplateColumns: '1fr 1fr',
        gap: 12,
        marginBottom: 16,
    },
    metaItem: {
        padding: 12,
        borderRadius: 8,
        background: esColors.pageBg,
        border: `1px solid ${esColors.border}`,
    },
    metaLabel: {
        margin: '0 0 4px',
        fontSize: 11,
        fontWeight: 600,
        color: esColors.muted,
        textTransform: 'uppercase',
        letterSpacing: '0.04em',
    },
    metaValue: {
        margin: 0,
        fontSize: 13,
        fontWeight: 600,
        color: esColors.text,
    },
    detailActions: {
        display: 'flex',
        flexWrap: 'wrap',
        gap: 8,
        marginBottom: 20,
    },
    sectionTitle: {
        margin: '0 0 12px',
        fontSize: 13,
        fontWeight: 700,
        color: esColors.text,
    },
    emptyHero: {
        ...esTheme.card,
        padding: '48px 32px',
        textAlign: 'center',
        maxWidth: 720,
        margin: '0 auto',
        boxShadow: '0 4px 24px rgba(15, 23, 42, 0.06)',
    },
    emptyIconWrap: {
        width: 72,
        height: 72,
        borderRadius: '50%',
        background: '#DBEAFE',
        color: esColors.primary,
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 20,
    },
    emptyTitle: {
        margin: '0 0 8px',
        fontSize: 20,
        fontWeight: 700,
        color: esColors.text,
    },
    emptyMessage: {
        margin: '0 auto 24px',
        fontSize: 14,
        color: esColors.muted,
        maxWidth: 480,
        lineHeight: 1.5,
    },
    stepsGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))',
        gap: 12,
        marginTop: 32,
        textAlign: 'left',
    },
    stepCard: {
        padding: 16,
        borderRadius: 10,
        border: `1px solid ${esColors.border}`,
        background: esColors.pageBg,
    },
    stepNum: {
        width: 28,
        height: 28,
        borderRadius: '50%',
        background: esColors.primary,
        color: '#fff',
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontSize: 13,
        fontWeight: 700,
        marginBottom: 10,
    },
    stepTitle: {
        margin: '0 0 4px',
        fontSize: 13,
        fontWeight: 700,
        color: esColors.text,
    },
    stepDesc: {
        margin: 0,
        fontSize: 12,
        color: esColors.muted,
        lineHeight: 1.45,
    },
    drawerOverlay: {
        position: 'fixed',
        inset: 0,
        background: 'rgba(15, 23, 42, 0.4)',
        zIndex: 60,
    },
    drawer: {
        position: 'fixed',
        top: 0,
        right: 0,
        bottom: 0,
        width: '100%',
        maxWidth: 440,
        background: esColors.white,
        boxShadow: '-8px 0 32px rgba(15, 23, 42, 0.12)',
        zIndex: 61,
        display: 'flex',
        flexDirection: 'column',
    },
    drawerHeader: {
        padding: '18px 20px',
        borderBottom: `1px solid ${esColors.border}`,
        display: 'flex',
        alignItems: 'flex-start',
        justifyContent: 'space-between',
        gap: 12,
    },
    drawerTitle: {
        margin: 0,
        fontSize: 17,
        fontWeight: 700,
        color: esColors.text,
    },
    drawerSubtitle: {
        margin: '4px 0 0',
        fontSize: 13,
        color: esColors.muted,
    },
    drawerBody: {
        flex: 1,
        overflow: 'auto',
        padding: '16px 20px',
    },
    drawerFooter: {
        padding: '14px 20px',
        borderTop: `1px solid ${esColors.border}`,
        display: 'flex',
        justifyContent: 'flex-end',
        gap: 8,
    },
    formField: {
        display: 'block',
        marginBottom: 14,
    },
    formLabel: {
        display: 'block',
        fontSize: 13,
        fontWeight: 600,
        marginBottom: 6,
        color: esColors.text,
    },
    formHint: {
        margin: '4px 0 0',
        fontSize: 11,
        color: esColors.muted,
    },
    formError: {
        margin: '0 0 14px',
        padding: '10px 12px',
        borderRadius: 8,
        background: '#FEF2F2',
        border: '1px solid #FECACA',
        color: '#B91C1C',
        fontSize: 13,
        lineHeight: 1.4,
    },
    formSection: {
        marginTop: 8,
        marginBottom: 14,
        paddingTop: 14,
        borderTop: `1px solid ${esColors.border}`,
    },
    formSectionTitle: {
        margin: '0 0 12px',
        fontSize: 12,
        fontWeight: 700,
        color: esColors.muted,
        textTransform: 'uppercase',
        letterSpacing: '0.04em',
    },
    checkboxRow: {
        display: 'flex',
        alignItems: 'center',
        gap: 8,
        fontSize: 13,
        color: esColors.text,
        marginBottom: 10,
    },
    toast: {
        padding: '12px 16px',
        borderRadius: 8,
        fontSize: 13,
        fontWeight: 500,
        display: 'flex',
        alignItems: 'center',
        gap: 8,
    },
    toastSuccess: {
        background: '#ECFDF5',
        border: '1px solid #A7F3D0',
        color: '#065F46',
    },
    toastError: {
        background: '#FEF2F2',
        border: '1px solid #FECACA',
        color: '#B91C1C',
    },
    pagination: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: '12px 16px',
        borderTop: `1px solid ${esColors.border}`,
        fontSize: 12,
        color: esColors.muted,
    },
    placeholderDetail: {
        ...esTheme.card,
        padding: 32,
        textAlign: 'center',
        color: esColors.muted,
        fontSize: 13,
    },
};
