import { esColors, esTheme } from '../../educacionSuperior/esTheme';

export const cceStyles = {
    tabs: {
        display: 'flex',
        gap: 4,
        borderBottom: `1px solid ${esColors.border}`,
        marginBottom: 20,
        flexWrap: 'wrap',
    },
    tab: {
        padding: '10px 16px',
        border: 'none',
        background: 'transparent',
        fontSize: 14,
        fontWeight: 500,
        color: esColors.muted,
        cursor: 'pointer',
        borderBottom: '2px solid transparent',
        marginBottom: -1,
    },
    tabActive: {
        color: esColors.primary,
        borderBottomColor: esColors.primary,
        fontWeight: 600,
    },
    card: { ...esTheme.card, padding: 16 },
    toolbar: {
        display: 'flex',
        flexWrap: 'wrap',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 12,
        marginBottom: 16,
    },
    toolbarFilters: {
        display: 'flex',
        flexWrap: 'wrap',
        alignItems: 'center',
        gap: 10,
        flex: 1,
    },
    badge: (color) => ({
        display: 'inline-flex',
        alignItems: 'center',
        gap: 6,
        padding: '3px 10px',
        borderRadius: 999,
        fontSize: 12,
        fontWeight: 600,
        background: color ? `${color}18` : '#F1F5F9',
        color: color || '#64748b',
        border: `1px solid ${color ? `${color}40` : '#E2E8F0'}`,
    }),
    badgeDot: (color) => ({
        width: 8,
        height: 8,
        borderRadius: '50%',
        background: color || '#64748b',
        flexShrink: 0,
    }),
    emptyState: {
        ...esTheme.card,
        padding: '48px 24px',
        textAlign: 'center',
    },
    emptyTitle: { margin: '0 0 8px', fontSize: 16, fontWeight: 600, color: esColors.text },
    emptyText: { margin: 0, fontSize: 14, color: esColors.muted, maxWidth: 420, marginInline: 'auto' },
    drawerOverlay: {
        position: 'fixed',
        inset: 0,
        background: 'rgba(15, 23, 42, 0.4)',
        zIndex: 1200,
    },
    drawer: {
        position: 'fixed',
        top: 0,
        right: 0,
        width: 'min(100%, 440px)',
        height: '100%',
        background: '#fff',
        zIndex: 1201,
        display: 'flex',
        flexDirection: 'column',
        boxShadow: '-8px 0 32px rgba(15, 23, 42, 0.12)',
    },
    drawerHeader: {
        padding: '20px 20px 12px',
        borderBottom: `1px solid ${esColors.border}`,
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        gap: 12,
    },
    drawerTitle: { margin: 0, fontSize: 18, fontWeight: 700, color: esColors.text },
    drawerSubtitle: { margin: '4px 0 0', fontSize: 13, color: esColors.muted },
    drawerBody: { padding: 20, overflowY: 'auto', flex: 1, display: 'flex', flexDirection: 'column', gap: 14 },
    drawerFooter: {
        padding: '16px 20px',
        borderTop: `1px solid ${esColors.border}`,
        display: 'flex',
        justifyContent: 'flex-end',
        gap: 8,
    },
    formField: { display: 'flex', flexDirection: 'column', gap: 6 },
    formLabel: { fontSize: 13, fontWeight: 600, color: esColors.text },
    formHint: { margin: 0, fontSize: 12, color: esColors.muted },
    formError: { margin: 0, fontSize: 13, color: '#DC2626', padding: '8px 12px', background: '#FEF2F2', borderRadius: 8 },
    checkboxRow: { display: 'flex', alignItems: 'center', gap: 8, fontSize: 14, color: esColors.text },
    toast: {
        position: 'fixed',
        bottom: 24,
        right: 24,
        zIndex: 1300,
        padding: '12px 16px',
        borderRadius: 10,
        fontSize: 14,
        display: 'flex',
        alignItems: 'center',
        gap: 12,
        maxWidth: 420,
        boxShadow: '0 8px 24px rgba(15,23,42,0.15)',
    },
    toastSuccess: { background: '#ECFDF5', color: '#065F46', border: '1px solid #A7F3D0' },
    toastError: { background: '#FEF2F2', color: '#991B1B', border: '1px solid #FECACA' },
    nombreCell: {
        display: 'inline-flex',
        alignItems: 'center',
        gap: 8,
        flexWrap: 'wrap',
    },
    nombreText: {
        fontSize: 13,
        fontWeight: 500,
        color: esColors.text,
    },
    colorBadge: (color) => ({
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        width: 22,
        height: 22,
        borderRadius: 6,
        background: color ? `${color}18` : '#F1F5F9',
        border: `1px solid ${color ? `${color}40` : '#E2E8F0'}`,
        flexShrink: 0,
    }),
    descripcionCell: {
        maxWidth: 360,
        fontSize: 13,
        color: esColors.muted,
        lineHeight: 1.45,
    },
    claveCode: {
        fontSize: 12,
        fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace',
        color: esColors.text,
        background: esColors.pageBg,
        padding: '2px 6px',
        borderRadius: 4,
        border: `1px solid ${esColors.border}`,
    },
    actionGroup: {
        display: 'inline-flex',
        alignItems: 'center',
        gap: 6,
        flexWrap: 'wrap',
    },
    actionBtn: {
        ...esTheme.btnSm,
        fontWeight: 500,
        color: esColors.text,
    },
    actionBtnEdit: {
        ...esTheme.btnSm,
        fontWeight: 500,
        color: esColors.primary,
        borderColor: `${esColors.primary}33`,
        background: `${esColors.primary}08`,
    },
    actionBtnToggle: (activo) => ({
        ...esTheme.btnSm,
        fontWeight: 500,
        color: activo ? esColors.warn : esColors.success,
        borderColor: activo ? `${esColors.warn}44` : `${esColors.success}44`,
        background: activo ? '#FFFBEB' : '#ECFDF5',
    }),
    readonlyHint: {
        fontSize: 12,
        color: esColors.mutedLight,
    },
};
