/** Tokens y estilos compartidos del módulo Educación Superior — editar aquí para cambiar toda el área. */
export const esColors = {
    primary: '#185FA5',
    success: '#0F6E56',
    warn: '#BA7517',
    danger: '#DC2626',
    purple: '#534AB7',
    text: '#0f172a',
    muted: '#64748b',
    mutedLight: '#94a3b8',
    border: '#e2e8f0',
    rowBorder: '#f1f5f9',
    pageBg: '#f8fafc',
    white: '#ffffff',
};

export const esTheme = {
    pageShell: {
        padding: '24px 32px',
        background: esColors.pageBg,
        minHeight: '100vh',
        fontFamily: 'system-ui, -apple-system, sans-serif',
    },
    card: {
        background: esColors.white,
        borderRadius: 12,
        border: `1px solid ${esColors.border}`,
        boxShadow: '0 1px 2px rgba(0,0,0,0.02)',
    },
    th: {
        background: esColors.pageBg,
        padding: '14px 16px',
        fontSize: 12,
        fontWeight: 600,
        color: esColors.muted,
        borderBottom: `1px solid ${esColors.border}`,
    },
    td: {
        padding: '16px',
        fontSize: 13,
    },
    tr: {
        borderBottom: `1px solid ${esColors.rowBorder}`,
    },
    iconBtn: {
        width: 30,
        height: 30,
        borderRadius: 8,
        border: `1px solid ${esColors.border}`,
        background: esColors.white,
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        cursor: 'pointer',
        textDecoration: 'none',
    },
    btnBase: {
        height: 40,
        padding: '0 16px',
        borderRadius: 8,
        display: 'inline-flex',
        alignItems: 'center',
        gap: 8,
        fontSize: 13,
        cursor: 'pointer',
    },
    btnSecondary: {
        height: 40,
        padding: '0 16px',
        borderRadius: 8,
        border: `1px solid ${esColors.border}`,
        background: esColors.white,
        display: 'inline-flex',
        alignItems: 'center',
        gap: 8,
        fontSize: 13,
        fontWeight: 500,
        color: esColors.text,
        cursor: 'pointer',
        textDecoration: 'none',
    },
    btnPrimary: {
        height: 40,
        padding: '0 16px',
        borderRadius: 8,
        background: esColors.primary,
        color: esColors.white,
        border: `1px solid ${esColors.primary}`,
        display: 'inline-flex',
        alignItems: 'center',
        gap: 8,
        fontSize: 13,
        fontWeight: 600,
        cursor: 'pointer',
        textDecoration: 'none',
    },
    btnSm: {
        border: `1px solid ${esColors.border}`,
        background: esColors.white,
        borderRadius: 8,
        padding: '6px 10px',
        fontSize: 12,
        cursor: 'pointer',
    },
    inputSearch: {
        height: 38,
        paddingLeft: 36,
        border: `1px solid ${esColors.border}`,
        borderRadius: 8,
        fontSize: 13,
        outline: 'none',
        background: esColors.white,
    },
    breadcrumb: {
        display: 'flex',
        alignItems: 'center',
        gap: 6,
        marginBottom: 8,
        fontSize: 13,
        color: esColors.primary,
        fontWeight: 500,
    },
    title: {
        margin: 0,
        fontSize: 32,
        fontWeight: 700,
        color: esColors.text,
    },
    titleLg: {
        margin: 0,
        fontSize: 34,
        fontWeight: 700,
        color: esColors.text,
    },
    subtitle: {
        margin: '8px 0 0',
        color: esColors.muted,
        fontSize: 14,
    },
    metricsGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(210px, 1fr))',
        gap: 16,
        marginBottom: 24,
    },
    metricsGridWide: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))',
        gap: 16,
        marginBottom: 24,
    },
    splitLayout: {
        display: 'grid',
        gridTemplateColumns: '1fr 320px',
        gap: 20,
        alignItems: 'start',
    },
    sidebarStack: {
        display: 'flex',
        flexDirection: 'column',
        gap: 20,
    },
    sectionTitle: {
        margin: 0,
        fontSize: 16,
        fontWeight: 700,
        color: esColors.text,
    },
    cardHeader: {
        padding: 16,
        borderBottom: `1px solid ${esColors.border}`,
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        gap: 12,
        flexWrap: 'wrap',
    },
    cardFooter: {
        padding: 16,
        borderTop: `1px solid ${esColors.border}`,
        fontSize: 12,
        color: esColors.muted,
    },
    cardFooterBetween: {
        padding: 16,
        borderTop: `1px solid ${esColors.border}`,
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        flexWrap: 'wrap',
        gap: 8,
        fontSize: 12,
        color: esColors.muted,
    },
    panelsGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))',
        gap: 20,
        marginTop: 24,
    },
    linkAccent: {
        fontSize: 12,
        color: esColors.primary,
        fontWeight: 600,
        textDecoration: 'none',
    },
    linkAccentMd: {
        fontSize: 13,
        color: esColors.primary,
        fontWeight: 600,
        textDecoration: 'none',
    },
    cardHeaderLg: {
        padding: '18px 20px',
        borderBottom: `1px solid ${esColors.border}`,
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        gap: 12,
        flexWrap: 'wrap',
    },
    sectionSubtitle: {
        margin: '4px 0 0',
        fontSize: 12,
        color: esColors.muted,
    },
    tdPrimary: {
        fontWeight: 600,
        color: esColors.primary,
    },
    tdEmphasis: {
        fontWeight: 500,
        color: esColors.text,
    },
    rowActions: {
        display: 'flex',
        gap: 8,
    },
    btnSmPrimary: {
        border: `1px solid ${esColors.border}`,
        background: esColors.white,
        borderRadius: 8,
        padding: '6px 10px',
        fontSize: 12,
        cursor: 'pointer',
        color: esColors.primary,
        textDecoration: 'none',
    },
    btnSmMuted: {
        border: `1px solid ${esColors.border}`,
        background: esColors.white,
        borderRadius: 8,
        padding: '6px 10px',
        fontSize: 12,
        cursor: 'pointer',
        color: esColors.muted,
        textDecoration: 'none',
    },
    sidebarStackSm: {
        display: 'flex',
        flexDirection: 'column',
        gap: 14,
    },
    emptyHint: {
        margin: 0,
        fontSize: 13,
        color: esColors.muted,
        textAlign: 'center',
    },
};

/** Colores de barras de progreso para reportes oficiales e indicadores. */
export const esProgressColors = {
    blue: esColors.primary,
    purple: esColors.purple,
    warn: esColors.warn,
    success: esColors.success,
};

export const esBadgeColors = {
    green: { background: '#DCFCE7', color: '#0F6E56' },
    yellow: { background: '#FEF3C7', color: '#BA7517' },
    red: { background: '#FEE2E2', color: '#DC2626' },
    blue: { background: '#DBEAFE', color: '#185FA5' },
    purple: { background: '#EDE9FE', color: '#534AB7' },
    gray: { background: '#F1F5F9', color: '#64748b' },
};

export const esHeaderVariants = {
    primary: { ...esTheme.btnBase, background: esColors.primary, color: esColors.white, border: `1px solid ${esColors.primary}`, fontWeight: 600, textDecoration: 'none' },
    success: { ...esTheme.btnBase, background: esColors.success, color: esColors.white, border: `1px solid ${esColors.success}`, fontWeight: 600, textDecoration: 'none' },
    warn: { ...esTheme.btnBase, background: '#FEF3C7', color: esColors.warn, border: '1px solid #FEF3C7', fontWeight: 600, textDecoration: 'none' },
    danger: { ...esTheme.btnBase, background: '#FEE2E2', color: esColors.danger, border: '1px solid #FEE2E2', fontWeight: 600, textDecoration: 'none' },
    secondary: { ...esTheme.btnSecondary, fontWeight: 500 },
};

export const esMetricTones = {
    blue: { iconBg: '#DBEAFE', iconColor: '#185FA5' },
    green: { iconBg: '#CCFBF1', iconColor: '#0F6E56' },
    teal: { iconBg: '#CCFBF1', iconColor: '#0F6E56' },
    purple: { iconBg: '#EDE9FE', iconColor: '#534AB7' },
    yellow: { iconBg: '#FEF3C7', iconColor: '#BA7517' },
    red: { iconBg: '#FEE2E2', iconColor: '#DC2626' },
};

export function formatEsNum(n) {
    return new Intl.NumberFormat('es-MX').format(Number(n) || 0);
}
